// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tolixnstpgukaktedhqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvbGl4bnN0cGd1a2FrdGVkaHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Nzc2OTQsImV4cCI6MjA1OTQ1MzY5NH0.9Z7jZVlRvT038WOmRjNrKmuzu0Vy3FmOz6UV0XXh5wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);